name: Rerun test and store report

# run because of a checkin, or because we want it to.
on:
  workflow_dispatch:
  push:
    branches:
      - master

# This is a run of the test suite because the test suite has been updated
# Therefore, the result id for information, and not directly controlling deployment
# Therefore, do not alter Stage (it may be in some transitional state), and get the result of running it against Live
jobs:
  testLive:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutTestware
        uses: actions/checkout@v2
        with:
          repository: KoalaTeaSoftware/eo-talismans-test
      - name: ensure that is running headless
        run: |
          cd src/test/configuration
          sed -i '/^windowSize/ s/^/#/' testFramework.properties
          sed -i '/^#windowSize=1920,1080/ s/^.*$/windowSize=1920,1080/' testFramework.properties
          sed -i '/headless=true/ s/^.*$/headless=true/' testFramework.properties
          cat  testFramework.properties
          echo "-----------------------------"
      - name: ensure that it is testing stage
        run: |
          cd src/test/configuration
          sed -i '/^defaultHost/ s/^/#/' systemUnderTest.properties
          sed -i '/defaultHost=earthoracles/ s/^#//' systemUnderTest.properties
          cat  systemUnderTest.properties
          echo "-----------------------------"
      - name: update the version information in the report
        run: |
          cd src/test/configuration
          sed -i "s/^buildNumber=.*$/buildNumber=CI Suite Update: $(git log -1 --pretty=format:%s)/" reporting.properties
          cat  reporting.properties
          echo "-----------------------------"
      - name: run the test
        run: mvn verify
      - name: Slack the failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Talsimans CI suite update - SUT fails tests
          MSG_MINIMAL: true
      - name: Notify test success by Slack
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: Talsimans CI suite update - SUT passes tests
          MSG_MINIMAL: true
      - name: upload test results to the display web site
        if: ${{ always() }}
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.koalateasoftware.com
          username: ${{ secrets.FTP_USER_REPORT }}
          password: ${{ secrets.FTP_PWD_REPORT }}
          local-dir: target/cucumber-html-reports/
          # the ftp account will write to /home2/koalate1/public_html/kts
          server-dir: web-site-development/earthoracles/cucumber-html-reports/
          # some of the files are given names that seem to be to do with tile-stamps, these need to be removed
          dangerous-clean-slate: true
